(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector
   ["#1E2029" "#ff5555" "#50fa7b" "#f1fa8c" "#61bfff" "#ff79c6" "#8be9fd" "#f8f8f2"])
 '(custom-safe-themes
   '("c7e22af1126cdcae96e5b0bd050db2fa7474f58da6b11597301f981f5084e536" "838d11ea964d3b396af1198064fc16794a0c0f952c26d4b39978ed60d55feb95" "a322d4aed44b7286403e3b35055d5956f7a4839672152afb11420616e83ddd8c" "e5f8d56f122ac600d6e196ba56d43fbb5be11d59d3e3b8497e612fe0f4984658" "912cac216b96560654f4f15a3a4d8ba47d9c604cbc3b04801e465fb67a0234f0" "2f1518e906a8b60fac943d02ad415f1d8b3933a5a7f75e307e6e9a26ef5bf570" "76bfa9318742342233d8b0b42e824130b3a50dcc732866ff8e47366aed69de11" default))
 '(fci-rule-color "#6272a4")
 '(jdee-db-active-breakpoint-face-colors (cons "#1E2029" "#bd93f9"))
 '(jdee-db-requested-breakpoint-face-colors (cons "#1E2029" "#50fa7b"))
 '(jdee-db-spec-breakpoint-face-colors (cons "#1E2029" "#565761"))
 '(newsticker-url-list
   '(("256PiAlternate" "http://vid.mint.lgbt:3000/feed/channel/UCMYN_nHr874uE8HOm0Dr3Ig" nil nil nil)
     ("2kliksphilip" "http://vid.mint.lgbt:3000/feed/channel/UCEKJKJ3FO-9SFv5x5BzyxhQ" nil nil nil)
     ("3kliksphilip" "http://vid.mint.lgbt:3000/feed/channel/UCmu9PVIZBk-ZCi-Sk2F2utA" nil nil nil)
     ("aahoff" "http://vid.mint.lgbt:3000/feed/channel/UCjlLVjI61-kG2UYDZfi7cnA" nil nil nil)
     ("ADoseofBuckley" "http://vid.mint.lgbt:3000/feed/channel/UC9kMnSZQd53hE-1sb1f9sdA" nil nil nil)
     ("Ahoy" "http://vid.mint.lgbt:3000/feed/channel/UCE1jXbVAGJQEORz9nZqb5bQ" nil nil nil)
     ("Akfamilyhome" "http://vid.mint.lgbt:3000/feed/channel/UCzyNtfiuGVAJ5Fo5iHz0jbQ" nil nil nil)
     ("AKindAleWar" "http://vid.mint.lgbt:3000/feed/channel/UCkQW6Qzjrg0jGnBkMER-vbA" nil nil nil)
     ("AlternateHistoryHub" "http://vid.mint.lgbt:3000/feed/channel/UClfEht64_NrzHf8Y0slKEjw" nil nil nil)
     ("AmyRightMeow" "http://vid.mint.lgbt:3000/feed/channel/UClN24S5-fc7LD0JJW0FdGWw" nil nil nil)
     ("An Odd World of Mine / ぼくのオッドワールド" "http://vid.mint.lgbt:3000/feed/channel/UCKo_UJkMFXQ5mNW-5auq_Ow" nil nil nil)
     ("Angie Speaks" "http://vid.mint.lgbt:3000/feed/channel/UCUtloyZ_Iu4BJekIqPLc_fQ" nil nil nil)
     ("Annotation Archive" "http://vid.mint.lgbt:3000/feed/channel/UCp_JnQg6SPItgtaqZEncP-w" nil nil nil)
     ("Arlo" "http://vid.mint.lgbt:3000/feed/channel/UC-9QiiVaViuqMhLp1XEwdxA" nil nil nil)
     ("Armoured Skeptic" "http://vid.mint.lgbt:3000/feed/channel/UC1BWMtZbNLVMSFgwSukjqCw" nil nil nil)
     ("ashens" "http://vid.mint.lgbt:3000/feed/channel/UCxt9Pvye-9x_AIcb1UtmF1Q" nil nil nil)
     ("Atomic Shrimp" "http://vid.mint.lgbt:3000/feed/channel/UCSl5Uxu2LyaoAoMMGp6oTJA" nil nil nil)
     ("AustinMcConnell" "http://vid.mint.lgbt:3000/feed/channel/UCbxQcz9k0NRRuy0ukgQTDQQ" nil nil nil)
     ("AvocaDon't" "http://vid.mint.lgbt:3000/feed/channel/UCevBgGOXXx12c4msoa_Ka0A" nil nil nil)
     ("BagelBoy" "http://vid.mint.lgbt:3000/feed/channel/UCwe5Z3D20uVMs0HG-faN4Lg" nil nil nil)
     ("BarrenDome" "http://vid.mint.lgbt:3000/feed/channel/UCpIvXT9VhAA1Z4_yReFgdBg" nil nil nil)
     ("Bedhead Bernie" "http://vid.mint.lgbt:3000/feed/channel/UCntBLn2xskJWKqMV40BqKJA" nil nil nil)
     ("Berd" "http://vid.mint.lgbt:3000/feed/channel/UCRei8TBpt4r0WPZ7MkiKmVg" nil nil nil)
     ("BG Kumbi" "http://vid.mint.lgbt:3000/feed/channel/UCm2pbaivKA-9poyXZ4rexrw" nil nil nil)
     ("Big Joel" "http://vid.mint.lgbt:3000/feed/channel/UCaN8DZdc8EHo5y1LsQWMiig" nil nil nil)
     ("bill wurtz" "http://vid.mint.lgbt:3000/feed/channel/UCq6aw03lNILzV96UvEAASfQ" nil nil nil)
     ("BionicPIG" "http://vid.mint.lgbt:3000/feed/channel/UCKyCNNJMe7dqlHhA8TRbe2A" nil nil nil)
     ("BluesDank" "http://vid.mint.lgbt:3000/feed/channel/UCQ-JI8Rz7PtS6nfmNoGKHxA" nil nil nil)
     ("Bobby Burns" "http://vid.mint.lgbt:3000/feed/channel/UCkaqF-7AO5ZHie0Rc-NEb2A" nil nil nil)
     ("Boyinaband" "http://vid.mint.lgbt:3000/feed/channel/UCQ4FyiI_1mWI2AtLS5ChdPQ" nil nil nil)
     ("Brian Matt Tokyo" "http://vid.mint.lgbt:3000/feed/channel/UC1QkDCNGtsEoYZ02qsAzQig" nil nil nil)
     ("brutalmoose" "http://vid.mint.lgbt:3000/feed/channel/UC18ju52OET36bdewLRHzPdQ" nil nil nil)
     ("BSoD Gaming" "http://vid.mint.lgbt:3000/feed/channel/UCex2B-k-ZIJhcjRdlYUz4MQ" nil nil nil)
     ("Caddicarus" "http://vid.mint.lgbt:3000/feed/channel/UCOkL7q2SeGZeZuj22njMYEA" nil nil nil)
     ("Captain Disillusion" "http://vid.mint.lgbt:3000/feed/channel/UCEOXxzW2vU0P-0THehuIIeg" nil nil nil)
     ("CaptainSparklez" "http://vid.mint.lgbt:3000/feed/channel/UCshoKvlZGZ20rVgazZp5vnQ" nil nil nil)
     ("CarlSagan42" "http://vid.mint.lgbt:3000/feed/channel/UClZbO3wehSIsPUKLx_X5caw" nil nil nil)
     ("carykh" "http://vid.mint.lgbt:3000/feed/channel/UC9z7EZAbkphEMg0SP7rw44A" nil nil nil)
     ("Cat Ghost" "http://vid.mint.lgbt:3000/feed/channel/UCwdmPCVOhTW2u_fKpxRLMdA" nil nil nil)
     ("Ceave Gaming" "http://vid.mint.lgbt:3000/feed/channel/UCFXc5nAao6554AIXlN9KgwQ" nil nil nil)
     ("CGP Grey" "http://vid.mint.lgbt:3000/feed/channel/UC2C_jShtL725hvbm1arSV9w" nil nil nil)
     ("Chadtronic" "http://vid.mint.lgbt:3000/feed/channel/UCcK72Xs5DAM3mnGpyImg63Q" nil nil nil)
     ("Channel Awesome" "http://vid.mint.lgbt:3000/feed/channel/UCiH828EtgQjTyNIMH6YiOSw" nil nil nil)
     ("Chaos Untold" "http://vid.mint.lgbt:3000/feed/channel/UCrLHbXQUCGShPPZuiMVSKmw" nil nil nil)
     ("Chi" "http://vid.mint.lgbt:3000/feed/channel/UC6mnQ7bAtcmPUJkdTypeThA" nil nil nil)
     ("ChickenPika" "http://vid.mint.lgbt:3000/feed/channel/UC3yypL1tHCMbOxRgAYjj_8g" nil nil nil)
     ("Chubbyemu" "http://vid.mint.lgbt:3000/feed/channel/UCKOvOaJv4GK-oDqx-sj7VVg" nil nil nil)
     ("Clementine ProductionsTM" "http://vid.mint.lgbt:3000/feed/channel/UCx3Raz47gMClQXQU00Is86g" nil nil nil)
     ("Coffee Break" "http://vid.mint.lgbt:3000/feed/channel/UC9WQRw8jgJhag-vkDNTDMRg" nil nil nil)
     ("ColdFusion" "http://vid.mint.lgbt:3000/feed/channel/UC4QZ_LsYcvcq7qOsOhpAX4A" nil nil nil)
     ("Company Man" "http://vid.mint.lgbt:3000/feed/channel/UCQMyhrt92_8XM0KgZH6VnRg" nil nil nil)
     ("Comrade Cora" "http://vid.mint.lgbt:3000/feed/channel/UCjyqR75IQwOROnq-HKBtWag" nil nil nil)
     ("ContraPoints" "http://vid.mint.lgbt:3000/feed/channel/UCNvsIonJdJ5E4EXMa65VYpA" nil nil nil)
     ("ContraPointsLive" "http://vid.mint.lgbt:3000/feed/channel/UCGh4KSR8TZZlyq3qQDBsBLA" nil nil nil)
     ("Count Dankula" "http://vid.mint.lgbt:3000/feed/channel/UC7SeFWZYFmsm1tqWxfuOTPQ" nil nil nil)
     ("cs188" "http://vid.mint.lgbt:3000/feed/channel/UCCSaQLMqanFT1GkHANX9w2w" nil nil nil)
     ("Cue 2" "http://vid.mint.lgbt:3000/feed/channel/UCIocsvyiCHCUFtHzkkMqZAw" nil nil nil)
     ("Cuestar" "http://vid.mint.lgbt:3000/feed/channel/UCuD71YaecVe2A1DVs3IldTA" nil nil nil)
     ("Cynical Reviews" "http://vid.mint.lgbt:3000/feed/channel/UC1DCPS2j-o0bvfIilkc8RSw" nil nil nil)
     ("Cyrakek" "http://vid.mint.lgbt:3000/feed/channel/UC3X-gn23KBEF7BA2NPwpsBQ" nil nil nil)
     ("Cyranek" "http://vid.mint.lgbt:3000/feed/channel/UCMYTaTc_gVRyGF6LWzdIsqA" nil nil nil)
     ("DaftPina" "http://vid.mint.lgbt:3000/feed/channel/UCxF3TRfs-MBdY_yM57ia9lQ" nil nil nil)
     ("Daniel T. Gaming" "http://vid.mint.lgbt:3000/feed/channel/UCXbpUY_Beh1uQA1_CH6bDxg" nil nil nil)
     ("Danny Gonzalez" "http://vid.mint.lgbt:3000/feed/channel/UCSUf5_EPEfl4zlBKZHkZdmw" nil nil nil)
     ("danooct1" "http://vid.mint.lgbt:3000/feed/channel/UCqbkm47qBxDj-P3lI9voIAw" nil nil nil)
     ("Dario Melofrias" "http://vid.mint.lgbt:3000/feed/channel/UCY2-VRTCuyI6xOsKRGUzqLw" nil nil nil)
     ("DaThings" "http://vid.mint.lgbt:3000/feed/channel/UCPd46rZJF4uDUfHWwxtlsQg" nil nil nil)
     ("deedumdim" "http://vid.mint.lgbt:3000/feed/channel/UCNkMMEt96y4eYmGoQjlvVSw" nil nil nil)
     ("Deleted Videos - DV" "http://vid.mint.lgbt:3000/feed/channel/UCGi4IVeY1LxOGNfhZgeGd2w" nil nil nil)
     ("DGR" "http://vid.mint.lgbt:3000/feed/channel/UCzg5UMJ62uoKHTkq5bgkp5g" nil nil nil)
     ("DigiDigger" "http://vid.mint.lgbt:3000/feed/channel/UCCa794oAhys-HzkqdfmnjdQ" nil nil nil)
     ("dinkie" "http://vid.mint.lgbt:3000/feed/channel/UCpmtFBOUJC2Y2KI6CN5gpWg" nil nil nil)
     ("DistroTube" "http://vid.mint.lgbt:3000/feed/channel/UCVls1GmFKf6WlTraIb_IaJg" nil nil nil)
     ("DizastaMusic" "http://vid.mint.lgbt:3000/feed/channel/UCqSHAXN5sqtyE93A-w-8Ddw" nil nil nil)
     ("Dodoid" "http://vid.mint.lgbt:3000/feed/channel/UCjbRaNcPVV9L58B0N18x1rg" nil nil nil)
     ("Dolan Dark" "http://vid.mint.lgbt:3000/feed/channel/UCt7E8Qpue2TU9Yh47vkEbsQ" nil nil nil)
     ("Dolan Darker" "http://vid.mint.lgbt:3000/feed/channel/UCI5qWAMf5PHLNcM13R8pfiQ" nil nil nil)
     ("Domics" "http://vid.mint.lgbt:3000/feed/channel/UCn1XB-jvmd9fXMzhiA6IR0w" nil nil nil)
     ("Dream" "http://vid.mint.lgbt:3000/feed/channel/UCTkXRDQl0luXxVQrRQvWS6w" nil nil nil)
     ("Drew Gooden" "http://vid.mint.lgbt:3000/feed/channel/UCTSRIY3GLFYIpkR2QwyeklA" nil nil nil)
     ("Dumbest of All Worlds" "http://vid.mint.lgbt:3000/feed/channel/UC4YNwIa0KQ455Ji2jYVLKFQ" nil nil nil)
     ("Ella Grant" "http://vid.mint.lgbt:3000/feed/channel/UCfnJvKB2Nr55ZvHj20O5JZA" nil nil nil)
     ("Elvis The Alien" "http://vid.mint.lgbt:3000/feed/channel/UChc-m3saf8K2oJHDSsnsj_A" nil nil nil)
     ("emilia fart" "http://vid.mint.lgbt:3000/feed/channel/UCgeyCSigD2EEv_D5evBRBWQ" nil nil nil)
     ("Emils Travel Vlog" "http://vid.mint.lgbt:3000/feed/channel/UCJgtf26h5a33oAphrRnM8eQ" nil nil nil)
     ("EmpLemon" "http://vid.mint.lgbt:3000/feed/channel/UC7Ucs42FZy3uYzjrqzOIHsw" nil nil nil)
     ("Ethan and Hila" "http://vid.mint.lgbt:3000/feed/channel/UC7pp40MU_6rLK5pvJYG3d0Q" nil nil nil)
     ("extraashens" "http://vid.mint.lgbt:3000/feed/channel/UCjscRSFwAXMnV7YN3vAR2Gw" nil nil nil)
     ("exurb1a" "http://vid.mint.lgbt:3000/feed/channel/UCimiUgDLbi6P17BdaCZpVbg" nil nil nil)
     ("exurb2a" "http://vid.mint.lgbt:3000/feed/channel/UCcoO-8J0EYQHGPFQqwmAzVQ" nil nil nil)
     ("Far Lands or Bust with KurtJMac" "http://vid.mint.lgbt:3000/feed/channel/UC1Un5592U9mFx5n6j2HyXow" nil nil nil)
     ("FrankJavCee" "http://vid.mint.lgbt:3000/feed/channel/UCAgoEUwn-LQy0fTyUxMngag" nil nil nil)
     ("Fresh Beats" "http://vid.mint.lgbt:3000/feed/channel/UCyZgsTMsYfvGGhhWk0ewTsA" nil nil nil)
     ("FUNKe" "http://vid.mint.lgbt:3000/feed/channel/UCd-qVRcjoK9zjtDs_LRxSmw" nil nil nil)
     ("G Dimmock" "http://vid.mint.lgbt:3000/feed/channel/UCBP83kEnLUkvxg9qvzdR57w" nil nil nil)
     ("GameGrumps" "http://vid.mint.lgbt:3000/feed/channel/UC9CuvdOVfMPvKCiwdGKL3cQ" nil nil nil)
     ("GD FuriousTiger" "http://vid.mint.lgbt:3000/feed/channel/UCw1GQix_DFBqzgYk4IEqmYA" nil nil nil)
     ("GeoWizard" "http://vid.mint.lgbt:3000/feed/channel/UCW5OrUZ4SeUYkUg1XqcjFYA" nil nil nil)
     ("GingerPale" "http://vid.mint.lgbt:3000/feed/channel/UCGGTAB19HlHEWPwwmxHsEKA" nil nil nil)
     ("GoldPlatedGoof" "http://vid.mint.lgbt:3000/feed/channel/UCtoBnL9JM0r_ZVXABGFkCyg" nil nil nil)
     ("Goose Boose" "http://vid.mint.lgbt:3000/feed/channel/UCPNpWbJonN_3pyeYATJb_bg" nil nil nil)
     ("Gorillaz" "http://vid.mint.lgbt:3000/feed/channel/UCfIXdjDQH9Fau7y99_Orpjw" nil nil nil)
     ("GradeAUnderA" "http://vid.mint.lgbt:3000/feed/channel/UCz7iJPVTBGX6DNO1RNI2Fcg" nil nil nil)
     ("Grandayy" "http://vid.mint.lgbt:3000/feed/channel/UCa6TeYZ2DlueFRne5DyAnyg" nil nil nil)
     ("grayfruit" "http://vid.mint.lgbt:3000/feed/channel/UCpFOj1CQMr9a3zaqEfhkTJw" nil nil nil)
     ("Green Ham Gaming" "http://vid.mint.lgbt:3000/feed/channel/UCmWRcMQyU-mGL1VRo2J3FuQ" nil nil nil)
     ("Grian" "http://vid.mint.lgbt:3000/feed/channel/UCR9Gcq0CMm6YgTzsDxAxjOQ" nil nil nil)
     ("H3 Podcast" "http://vid.mint.lgbt:3000/feed/channel/UCLtREJY21xRfCuEKvdki1Kw" nil nil nil)
     ("h3h3Productions" "http://vid.mint.lgbt:3000/feed/channel/UCDWIvJwLJsE4LG1Atne2blQ" nil nil nil)
     ("Hazel Cricket" "http://vid.mint.lgbt:3000/feed/channel/UCasKvuIk59T7SUJr60auxqg" nil nil nil)
     ("hbomberguy" "http://vid.mint.lgbt:3000/feed/channel/UClt01z1wHHT7c5lKcU8pxRQ" nil nil nil)
     ("Henke" "http://vid.mint.lgbt:3000/feed/channel/UCT-dZgkszzTU6ObHpETK-yg" nil nil nil)
     ("Historia Civilis" "http://vid.mint.lgbt:3000/feed/channel/UCv_vLHiWVBh_FR9vbeuiY-A" nil nil nil)
     ("hitsuyo" "http://vid.mint.lgbt:3000/feed/channel/UCSPutMoZCm6g4xtxv1YhiJA" nil nil nil)
     ("Holy Koolaid" "http://vid.mint.lgbt:3000/feed/channel/UCzvoUDoDu-cKIb11rg4ODDQ" nil nil nil)
     ("Hot Dad" "http://vid.mint.lgbt:3000/feed/channel/UCGY2w6hIZWwyxasBUN7wbaQ" nil nil nil)
     ("hotdiggedydemon" "http://vid.mint.lgbt:3000/feed/channel/UCmvXfmJEtURCEtHNbMXfDqg" nil nil nil)
     ("Huggbees" "http://vid.mint.lgbt:3000/feed/channel/UC8CsGpP6kVNrWeBVmlJ2UyA" nil nil nil)
     ("I Hate Everything" "http://vid.mint.lgbt:3000/feed/channel/UCRbOPaGDB_xOQkVM8Rnn62Q" nil nil nil)
     ("ibx2cat" "http://vid.mint.lgbt:3000/feed/channel/UCJVnko6tQ56PYB5BNNChPGg" nil nil nil)
     ("ibxtoycat" "http://vid.mint.lgbt:3000/feed/channel/UC_GQ4mac4oN3wl1UdbFuTEA" nil nil nil)
     ("iDubbbzgames" "http://vid.mint.lgbt:3000/feed/channel/UCVhfFXNY0z3-mbrTh1OYRXA" nil nil nil)
     ("iDubbbzTV" "http://vid.mint.lgbt:3000/feed/channel/UC4USoIAL9qcsx5nCZV_QRnA" nil nil nil)
     ("iDubbbzTV2" "http://vid.mint.lgbt:3000/feed/channel/UC-tsNNJ3yIW98MtPH6PWFAQ" nil nil nil)
     ("illymation" "http://vid.mint.lgbt:3000/feed/channel/UCsKVP_4zQ877TEiH_Ih5yDQ" nil nil nil)
     ("ilmango" "http://vid.mint.lgbt:3000/feed/channel/UCHSI8erNrN6hs3sUK6oONLA" nil nil nil)
     ("ImAllexx" "http://vid.mint.lgbt:3000/feed/channel/UCki1I0RCzDl2TX_5GXyrGaw" nil nil nil)
     ("Internet Comment Etiquette with Erik" "http://vid.mint.lgbt:3000/feed/channel/UCyWDmyZRjrGHeKF-ofFsT5Q" nil nil nil)
     ("Internet Historian: Incognito Mode" "http://vid.mint.lgbt:3000/feed/channel/UC8Q7XEy86Q7T-3kNpNjYgwA" nil nil nil)
     ("Internet Sensation" "http://vid.mint.lgbt:3000/feed/channel/UCjLtsY7SSN5cq1Riecqxn5Q" nil nil nil)
     ("Iriyo" "http://vid.mint.lgbt:3000/feed/channel/UC3YI1z-H6kE-_ZxGVGdWYpQ" nil nil nil)
     ("iskall85" "http://vid.mint.lgbt:3000/feed/channel/UCZ9x-z3iOnIbJxVpm1rsu2A" nil nil nil)
     ("It's a small world" "http://vid.mint.lgbt:3000/feed/channel/UCbvQHCZJHHS4PJpatQGH-0w" nil nil nil)
     ("j aubrey" "http://vid.mint.lgbt:3000/feed/channel/UCYvEb6iLPxLPZTe6NcUUUeA" nil nil nil)
     ("J's Reviews" "http://vid.mint.lgbt:3000/feed/channel/UCOiqB1MjAZpaq4m8WIoqQAw" nil nil nil)
     ("Jack Saint" "http://vid.mint.lgbt:3000/feed/channel/UCdQKvqmHKe_8fv4Rwe7ag9Q" nil nil nil)
     ("jacksfilms" "http://vid.mint.lgbt:3000/feed/channel/UCPcFg7aBbaVzXoIKSNqwaww" nil nil nil)
     ("Jaiden Animations" "http://vid.mint.lgbt:3000/feed/channel/UCGwu0nbY2wSkW8N-cghnLpA" nil nil nil)
     ("James Marriott" "http://vid.mint.lgbt:3000/feed/channel/UCwM8W2IEsCLRQWc6krOlRVw" nil nil nil)
     ("Jarvis Johnson" "http://vid.mint.lgbt:3000/feed/channel/UCoLUji8TYrgDy74_iiazvYA" nil nil nil)
     ("Jarvis Johnson Tech" "http://vid.mint.lgbt:3000/feed/channel/UCdjWvAZC4FXaOI9_puALhTg" nil nil nil)
     ("Jeremiah 76" "http://vid.mint.lgbt:3000/feed/channel/UCIEdiIqKxc34DCWdVBgFOLw" nil nil nil)
     ("Jesus Christ" "http://vid.mint.lgbt:3000/feed/channel/UCJY99Kt7cpA1XlPhaonGtvQ" nil nil nil)
     ("Jim Sterling" "http://vid.mint.lgbt:3000/feed/channel/UCWCw2Sd7RlYJ2yuNVHDWNOA" nil nil nil)
     ("Jimmy Snow" "http://vid.mint.lgbt:3000/feed/channel/UCgeV3tFiU2Xg0PD1dAQbBHA" nil nil nil)
     ("Jmak" "http://vid.mint.lgbt:3000/feed/channel/UCLVtdJWbRGhDeivbGxaLsZQ" nil nil nil)
     ("Joey Pockett" "http://vid.mint.lgbt:3000/feed/channel/UC1dDig68uYf_1QM7GJ9ecTA" nil nil nil)
     ("Jon Sudano" "http://vid.mint.lgbt:3000/feed/channel/UCYmBRsXr995owHHryHYPzFQ" nil nil nil)
     ("Jonathan Aldrich" "http://vid.mint.lgbt:3000/feed/channel/UCq40ak4VJQW0ZICTcPCY3mw" nil nil nil)
     ("JonTronShow" "http://vid.mint.lgbt:3000/feed/channel/UCdJdEguB1F1CiYe7OEi3SBg" nil nil nil)
     ("Jordan" "http://vid.mint.lgbt:3000/feed/channel/UCpU7uo9AeR5b9Gcu2t70mQQ" nil nil nil)
     ("Jreg" "http://vid.mint.lgbt:3000/feed/channel/UCGSGPehp0RWfca-kENgBJ9Q" nil nil nil)
     ("Justin Kuritzkes" "http://vid.mint.lgbt:3000/feed/channel/UCNdFtR-glRU4MbKGtgEqpeQ" nil nil nil)
     ("Kat Blaque" "http://vid.mint.lgbt:3000/feed/channel/UCxFWzKZa74SyAqpJyVlG5Ew" nil nil nil)
     ("Keralis" "http://vid.mint.lgbt:3000/feed/channel/UCcJgOennb0II4a_qi9OMkRA" nil nil nil)
     ("Kitboga" "http://vid.mint.lgbt:3000/feed/channel/UCm22FAXZMw1BaWeFszZxUKw" nil nil nil)
     ("Kleric" "http://vid.mint.lgbt:3000/feed/channel/UC4BGutC_CNefeMLs24-XZFA" nil nil nil)
     ("Kneecap Jake" "http://vid.mint.lgbt:3000/feed/channel/UCZp7F3xG5DBBA-t7AEK9kGA" nil nil nil)
     ("Kneecap Jake" "http://vid.mint.lgbt:3000/feed/channel/UCn_PUPqDHcdNDFDzZMO5INQ" nil nil nil)
     ("Knowing Better" "http://vid.mint.lgbt:3000/feed/channel/UC8XjmAEDVZSCQjI150cb4QA" nil nil nil)
     ("KnowledgeHub" "http://vid.mint.lgbt:3000/feed/channel/UC2_KC8lshtCyiLApy27raYw" nil nil nil)
     ("Kurtis Conner" "http://vid.mint.lgbt:3000/feed/channel/UC7zsxKqd5MicTf4VhS9Y74g" nil nil nil)
     ("Kurzgesagt – In a Nutshell" "http://vid.mint.lgbt:3000/feed/channel/UCsXVk37bltHxD1rDPwtNM8Q" nil nil nil)
     ("Laddi" "http://vid.mint.lgbt:3000/feed/channel/UCI-92EMS3ZJ11gz-S_oyaSA" nil nil nil)
     ("Leftist Tech Support" "http://vid.mint.lgbt:3000/feed/channel/UCv75kypdQZpwQ9avEnDYF8A" nil nil nil)
     ("legomasta99" "http://vid.mint.lgbt:3000/feed/channel/UCm6CQ7_2jmt0q43aW5mDtVA" nil nil nil)
     ("Leon Lush" "http://vid.mint.lgbt:3000/feed/channel/UCLHsZ4X7YemjxRrvq0AI4LA" nil nil nil)
     ("let's talk about stuff." "http://vid.mint.lgbt:3000/feed/channel/UCjSJq8eE73nCc9mtSMkNh6g" nil nil nil)
     ("LGR" "http://vid.mint.lgbt:3000/feed/channel/UCLx053rWZxCiYWsBETgdKrQ" nil nil nil)
     ("Lindsay Ellis" "http://vid.mint.lgbt:3000/feed/channel/UCG1h-Wqjtwz7uUANw6gazRw" nil nil nil)
     ("Lockstin & Gnoggin" "http://vid.mint.lgbt:3000/feed/channel/UC6sjkvDzyY0J8o7k2Kc5rEw" nil nil nil)
     ("Logdotzip" "http://vid.mint.lgbt:3000/feed/channel/UC2D-GCxeE69hCUmRwISXABw" nil nil nil)
     ("Louis Rossmann" "http://vid.mint.lgbt:3000/feed/channel/UCl2mFZoRqjw_ELax4Yisf6w" nil nil nil)
     ("MamaMax" "http://vid.mint.lgbt:3000/feed/channel/UCpofQJ6RpHrxuUG4ghXPJBA" nil nil nil)
     ("Marshal Does Stuff" "http://vid.mint.lgbt:3000/feed/channel/UCyFjeoG9X83dVWHKqXCKwHg" nil nil nil)
     ("Matt and Tom" "http://vid.mint.lgbt:3000/feed/channel/UCRUULstZRWS1lDvJBzHnkXA" nil nil nil)
     ("Mayro" "http://vid.mint.lgbt:3000/feed/channel/UCumgUoIV9t2aGtaQXmwXIAg" nil nil nil)
     ("MEANS TV" "http://vid.mint.lgbt:3000/feed/channel/UC3VHfy8e1jbDnT5TG2pjP1w" nil nil nil)
     ("MEGA CHANNEL" "http://vid.mint.lgbt:3000/feed/channel/UCQVL8LiVla2sZks_jQSQitg" nil nil nil)
     ("Memeski" "http://vid.mint.lgbt:3000/feed/channel/UCIKbdv5nUqdo_clAyfcxAeQ" nil nil nil)
     ("Mess Music TV" "http://vid.mint.lgbt:3000/feed/channel/UCT4uWGYjWq9Rb-vf1F_qofw" nil nil nil)
     ("Michael `Jasper` Ashworth" "http://vid.mint.lgbt:3000/feed/channel/UC5bN6XKHDCFt_wYAJmsP_Mg" nil nil nil)
     ("Michael Reeves" "http://vid.mint.lgbt:3000/feed/channel/UCtHaxi4GTYDpJgMSGy7AeSw" nil nil nil)
     ("minutephysics" "http://vid.mint.lgbt:3000/feed/channel/UCUHW94eEFW7hkUMVaZz4eDg" nil nil nil)
     ("MixAndMash" "http://vid.mint.lgbt:3000/feed/channel/UCg8kyjXQE561Dh_2DdDI8AA" nil nil nil)
     ("MowtenDoo" "http://vid.mint.lgbt:3000/feed/channel/UCYFvEPbFbDIVRiODrh1-x4g" nil nil nil)
     ("MowtenDoos Alt" "http://vid.mint.lgbt:3000/feed/channel/UCEyeAscGBqaV_qjfYlL9Szw" nil nil nil)
     ("MrBeast" "http://vid.mint.lgbt:3000/feed/channel/UCX6OQ3DkcsbYNE6H8uQQuVA" nil nil nil)
     ("mrgirl" "http://vid.mint.lgbt:3000/feed/channel/UCMDtmBswP2NR4R_WjKUSn6A" nil nil nil)
     ("Mumbo Jumbo" "http://vid.mint.lgbt:3000/feed/channel/UChFur_NwVSbUozOcF_F2kMg" nil nil nil)
     ("Nate TV" "http://vid.mint.lgbt:3000/feed/channel/UCElMK9CA8GEInVs6afehiRA" nil nil nil)
     ("Nerd City" "http://vid.mint.lgbt:3000/feed/channel/UCxsQFG_8Dbt1sZhLReL2mUw" nil nil nil)
     ("Nerd on the Street - Tech" "http://vid.mint.lgbt:3000/feed/channel/UCc6MhFTqnuIpEGgLBm_jwtw" nil nil nil)
     ("Nerrel" "http://vid.mint.lgbt:3000/feed/channel/UCZKyj7wDE51SMbkrRBT6SdA" nil nil nil)
     ("NFKRZ" "http://vid.mint.lgbt:3000/feed/channel/UC19xLluI7dG093Gmw57BhHw" nil nil nil)
     ("Nick Maley" "http://vid.mint.lgbt:3000/feed/channel/UCztgnpl_ehYEk8I7d1KUcQw" nil nil nil)
     ("Nick Robinson" "http://vid.mint.lgbt:3000/feed/channel/UCOuddH5GyBXp-_tv_ASdp_A" nil nil nil)
     ("Night Mind" "http://vid.mint.lgbt:3000/feed/channel/UC58IKuPHnZkdCZ6T5mSRGCg" nil nil nil)
     ("NonCompete" "http://vid.mint.lgbt:3000/feed/channel/UCkZFKKK-0YB0FvwoS8P7nHg" nil nil nil)
     ("Noodle" "http://vid.mint.lgbt:3000/feed/channel/UCj74rJ9Lgl3WTngq675wxKg" nil nil nil)
     ("Nullatrum" "http://vid.mint.lgbt:3000/feed/channel/UC9qURpEWWIA2jbxLBRItksQ" nil nil nil)
     ("Oblivifrek" "http://vid.mint.lgbt:3000/feed/channel/UCjoPN5N9GqlnC_-1Y6CejTA" nil nil nil)
     ("pamtri" "http://vid.mint.lgbt:3000/feed/channel/UCYBP_TtboAYP28U3ZVNM9Ig" nil nil nil)
     ("PantslessPajamas" "http://vid.mint.lgbt:3000/feed/channel/UCR0O-1cvuPNxDosvSDLpWHg" nil nil nil)
     ("Particular Mushroom" "http://vid.mint.lgbt:3000/feed/channel/UCgMRN6BYxIMAim0dx_wbofQ" nil nil nil)
     ("PeanutButterGamer" "http://vid.mint.lgbt:3000/feed/channel/UCRBkeMoYX02w-0qVIKNkruw" nil nil nil)
     ("penguinz0" "http://vid.mint.lgbt:3000/feed/channel/UCq6VFHwMzcMXbuKyG7SQYIg" nil nil nil)
     ("Peter Coffin" "http://vid.mint.lgbt:3000/feed/channel/UCT5jxI_OYY2r--TjAGXD03A" nil nil nil)
     ("Peter Knetter" "http://vid.mint.lgbt:3000/feed/channel/UCNMyoMaXJZITZaRKCz7G23Q" nil nil nil)
     ("Petscop" "http://vid.mint.lgbt:3000/feed/channel/UCZKQv0ZFHpeIUkOtNjtq4KA" nil nil nil)
     ("PewDiePie" "http://vid.mint.lgbt:3000/feed/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw" nil nil nil)
     ("Philosophy Tube" "http://vid.mint.lgbt:3000/feed/channel/UC2PA-AKmVpU6NKCGtZq_rKQ" nil nil nil)
     ("Phoenix SC" "http://vid.mint.lgbt:3000/feed/channel/UCj4zC1Hfj-uc90FUXzRamNw" nil nil nil)
     ("Pikasprey Blue" "http://vid.mint.lgbt:3000/feed/channel/UCZJVzJk_24aefzpKAbqiP9Q" nil nil nil)
     ("Pinely" "http://vid.mint.lgbt:3000/feed/channel/UCiHRg_hyyHQe_IZ-efHR5Vg" nil nil nil)
     ("Polygon" "http://vid.mint.lgbt:3000/feed/channel/UCuVxaQDraOja6xKidcmoufA" nil nil nil)
     ("Professor Toot" "http://vid.mint.lgbt:3000/feed/channel/UCo00SQBQyS3y1_s3clWn3fQ" nil nil nil)
     ("ProJared Plays!" "http://vid.mint.lgbt:3000/feed/channel/UCi7GVfMNROkrw5F2YrdBkNw" nil nil nil)
     ("punpun" "http://vid.mint.lgbt:3000/feed/channel/UCGd0ejnHTstpIyB2V_1mFNg" nil nil nil)
     ("Pyrocynical" "http://vid.mint.lgbt:3000/feed/channel/UCN5xN8gIljvWYnsj06V8WbQ" nil nil nil)
     ("PyrocynicalVEVO" "http://vid.mint.lgbt:3000/feed/channel/UCdc_JyNaB5VJ0gdWUtWfGDg" nil nil nil)
     ("Quackity" "http://vid.mint.lgbt:3000/feed/channel/UC_8NknAFiyhOUaZqHR3lq3Q" nil nil nil)
     ("Quinton Reviews" "http://vid.mint.lgbt:3000/feed/channel/UCM0V8r4kuIWIl6Sy-NHj2lg" nil nil nil)
     ("ralphthemoviemaker" "http://vid.mint.lgbt:3000/feed/channel/UCZ04pLI44c0PWRzubEV6ogA" nil nil nil)
     ("READY TO GLARE" "http://vid.mint.lgbt:3000/feed/channel/UC1nJzvNaB_ql4RHrzgozrQQ" nil nil nil)
     ("RebelTaxi" "http://vid.mint.lgbt:3000/feed/channel/UCN3Jj2sU9LNFQplsjsdxdrw" nil nil nil)
     ("RedExec" "http://vid.mint.lgbt:3000/feed/channel/UC6crzPo5bTilPqaPqRvRiYQ" nil nil nil)
     ("ReignBot" "http://vid.mint.lgbt:3000/feed/channel/UCchWU8ta6L-Dy3rGIxPINzw" nil nil nil)
     ("RelaxAlax" "http://vid.mint.lgbt:3000/feed/channel/UCkmP59n7648ESU0PJsJMiRw" nil nil nil)
     ("RennsReviews" "http://vid.mint.lgbt:3000/feed/channel/UCLfE_XQ_Xfmsh-N1iwS3PtQ" nil nil nil)
     ("Retro Game Mechanics Explained" "http://vid.mint.lgbt:3000/feed/channel/UCwRqWnW5ZkVaP_lZF7caZ-g" nil nil nil)
     ("RTGame" "http://vid.mint.lgbt:3000/feed/channel/UCRC6cNamj9tYAO6h_RXd5xA" nil nil nil)
     ("RTGame Stream Archive" "http://vid.mint.lgbt:3000/feed/channel/UCyUmevTef0H-pFaspmfTb3Q" nil nil nil)
     ("Saberspark" "http://vid.mint.lgbt:3000/feed/channel/UCeGGpOehPGG7vQMUVc7tG8Q" nil nil nil)
     ("salt" "http://vid.mint.lgbt:3000/feed/channel/UCbfWcuV3SNZV4ywuOMhtJDQ" nil nil nil)
     ("Sam O'Nella Academy" "http://vid.mint.lgbt:3000/feed/channel/UC1DTYW241WD64ah5BFWn4JA" nil nil nil)
     ("Scott The Woz" "http://vid.mint.lgbt:3000/feed/channel/UC4rqhyiTs7XyuODcECvuiiQ" nil nil nil)
     ("Sealow" "http://vid.mint.lgbt:3000/feed/channel/UCnihwbgoknQaHO6XT_K3mtA" nil nil nil)
     ("Sean Hogan" "http://vid.mint.lgbt:3000/feed/channel/UC1Fz5YWpwDUV66YLURRQp3w" nil nil nil)
     ("shane" "http://vid.mint.lgbt:3000/feed/channel/UCV9_KinVpV-snHe3C3n1hvA" nil nil nil)
     ("Sheriff Domestic" "http://vid.mint.lgbt:3000/feed/channel/UCuUYNNMCesM23ZVCcApLTCA" nil nil nil)
     ("Shesez" "http://vid.mint.lgbt:3000/feed/channel/UCHTnEwQKNwm49CQeCVZogMw" nil nil nil)
     ("Shitpost Wizard" "http://vid.mint.lgbt:3000/feed/channel/UCUAd9ezG7jB1VEZhQ3nV66g" nil nil nil)
     ("SiIvaGunner" "http://vid.mint.lgbt:3000/feed/channel/UC9ecwl3FTG66jIKA9JRDtmg" nil nil nil)
     ("SiIvaGunner2" "http://vid.mint.lgbt:3000/feed/channel/UCYGz7FZImRL8oI68pD7NoKg" nil nil nil)
     ("SimpleFlips" "http://vid.mint.lgbt:3000/feed/channel/UCiYpKsB66LZsk7s4yhxJqlQ" nil nil nil)
     ("Slazo" "http://vid.mint.lgbt:3000/feed/channel/UC5zUt-9qSFHF8if6TQBq6CA" nil nil nil)
     ("Slimecicle" "http://vid.mint.lgbt:3000/feed/channel/UCQmzgjEb7X6--w7CSE1erJg" nil nil nil)
     ("SmallAnt" "http://vid.mint.lgbt:3000/feed/channel/UC0VVYtw21rg2cokUystu2Dw" nil nil nil)
     ("SomeOrdinaryGamers" "http://vid.mint.lgbt:3000/feed/channel/UCtMVHI3AJD4Qk4hcbZnI9ZQ" nil nil nil)
     ("SomeThingElseYT" "http://vid.mint.lgbt:3000/feed/channel/UCvUmwreRrbxeR1mbmojj8fg" nil nil nil)
     ("SootHouse" "http://vid.mint.lgbt:3000/feed/channel/UCU4dU07ZfRopBQroeYdpWIA" nil nil nil)
     ("Sorrow TV" "http://vid.mint.lgbt:3000/feed/channel/UCbT9KeTO_xETnqqsp5oQ3UA" nil nil nil)
     ("Speggi" "http://vid.mint.lgbt:3000/feed/channel/UCbTvL2iGT_R9Ld4M46xO3AQ" nil nil nil)
     ("Spooky Scary Socialist" "http://vid.mint.lgbt:3000/feed/channel/UCl_A_42M6kvjH8Gr-rwfCUw" nil nil nil)
     ("Stefan Karl" "http://vid.mint.lgbt:3000/feed/channel/UCZiqc1Zq_1TYr8wRlCpx-Qg" nil nil nil)
     ("STRANGE ÆONS" "http://vid.mint.lgbt:3000/feed/channel/UCrq3JYirgV-BLluzTF6X_7A" nil nil nil)
     ("Stressmonster101" "http://vid.mint.lgbt:3000/feed/channel/UC24lkOxZYna9nlXYBcJ9B8Q" nil nil nil)
     ("Stryder7x" "http://vid.mint.lgbt:3000/feed/channel/UCYDnJiF0_RqSjkjvjRbG1tA" nil nil nil)
     ("Summoning Salt" "http://vid.mint.lgbt:3000/feed/channel/UCtUbO6rBht0daVIOGML3c8w" nil nil nil)
     ("Suris" "http://vid.mint.lgbt:3000/feed/channel/UCh-YXgnF0tmBxCsh4w_4svw" nil nil nil)
     ("SwankyBox" "http://vid.mint.lgbt:3000/feed/channel/UCF0SRAnWz56UBv-upYD0B5Q" nil nil nil)
     ("Switch Stop" "http://vid.mint.lgbt:3000/feed/channel/UCBHQQLFpwRuZzLtAqbvoH2A" nil nil nil)
     ("Tabbes" "http://vid.mint.lgbt:3000/feed/channel/UCDQBZcjYKP1J1Nu-Y0_D37Q" nil nil nil)
     ("tamago2474" "http://vid.mint.lgbt:3000/feed/channel/UCpLw_vyY6pDFIKhPGTSTLKw" nil nil nil)
     ("Techlore" "http://vid.mint.lgbt:3000/feed/channel/UCs6KfncB4OV6Vug4o_bzijg" nil nil nil)
     ("Techquickie" "http://vid.mint.lgbt:3000/feed/channel/UC0vBXGSyV14uvJ4hECDOl0Q" nil nil nil)
     ("Telltale" "http://vid.mint.lgbt:3000/feed/channel/UCgIi12EA6BQ8HKL8QUccsOQ" nil nil nil)
     ("The Hated One" "http://vid.mint.lgbt:3000/feed/channel/UCjr2bPAyPV7t35MvcgT3W8Q" nil nil nil)
     ("The Right Opinion" "http://vid.mint.lgbt:3000/feed/channel/UCMTk_R_Y49jvq-HQXDmKI0Q" nil nil nil)
     ("The Science Elf" "http://vid.mint.lgbt:3000/feed/channel/UCCrnCItH17W-64FDzjwOi5w" nil nil nil)
     ("The Tommy Edison Experience" "http://vid.mint.lgbt:3000/feed/channel/UCld5SlwHrXgAYRE83WJOPCw" nil nil nil)
     ("The Wraith" "http://vid.mint.lgbt:3000/feed/channel/UCii-yMeVDX7ZPjHjv0OXqIg" nil nil nil)
     ("TheLonelyGoomba" "http://vid.mint.lgbt:3000/feed/channel/UClp8Q_hqVtDotkDDKh4po3Q" nil nil nil)
     ("theneedledrop" "http://vid.mint.lgbt:3000/feed/channel/UCt7fwAhXDy3oNFTAzF2o8Pw" nil nil nil)
     ("TheOdd1sOut" "http://vid.mint.lgbt:3000/feed/channel/UCo8bcnLyZH8tBIH9V1mLgqQ" nil nil nil)
     ("TheOdd2sOut" "http://vid.mint.lgbt:3000/feed/channel/UC0GLNhtTu7yI8rl6ZZGeezw" nil nil nil)
     ("TheraminTrees" "http://vid.mint.lgbt:3000/feed/channel/UCJ-vHE5CrGaL_ITEg-n3OeA" nil nil nil)
     ("TheReportOfTheWeek" "http://vid.mint.lgbt:3000/feed/channel/UCeR0n8d3ShTn_yrMhpwyE1Q" nil nil nil)
     ("TheSMonroeShow" "http://vid.mint.lgbt:3000/feed/channel/UCwrQ7Wq0AzzEgKVfk5tr1Pg" nil nil nil)
     ("Thomas Game Docs" "http://vid.mint.lgbt:3000/feed/channel/UCyy7dZhgfeMMctSoo3wDXlQ" nil nil nil)
     ("Those Awesome Guys" "http://vid.mint.lgbt:3000/feed/channel/UCG58a6GgIu3z-NlTeDetXuA" nil nil nil)
     ("Thought Slime" "http://vid.mint.lgbt:3000/feed/channel/UCrr7y8rEXb7_RiVniwvzk9w" nil nil nil)
     ("Three Arrows" "http://vid.mint.lgbt:3000/feed/channel/UCCT8a7d6S6RJUivBgNRsiYg" nil nil nil)
     ("Thunderf00t" "http://vid.mint.lgbt:3000/feed/channel/UCmb8hO2ilV9vRa8cilis88A" nil nil nil)
     ("TLDR News" "http://vid.mint.lgbt:3000/feed/channel/UCSMqateX8OA2s1wsOR2EgJA" nil nil nil)
     ("tolbot.exe" "http://vid.mint.lgbt:3000/feed/channel/UCuOCZlxUEqIu9YKxkOK6EAQ" nil nil nil)
     ("Tom Scott" "http://vid.mint.lgbt:3000/feed/channel/UCBa659QWEk1AI4Tg--mrJ2A" nil nil nil)
     ("Toms Mucenieks" "http://vid.mint.lgbt:3000/feed/channel/UCfWXf5EvbPUxrN7vFDspDQQ" nil nil nil)
     ("Torbulous" "http://vid.mint.lgbt:3000/feed/channel/UCqfUdsFcT0HiHtJ-TYKU9yA" nil nil nil)
     ("Turkey Tom" "http://vid.mint.lgbt:3000/feed/channel/UCDKJdFer1phQI95UinPZehw" nil nil nil)
     ("TVFilthyFrank" "http://vid.mint.lgbt:3000/feed/channel/UCkitABalXafr-NqceQdDXtg" nil nil nil)
     ("TWD98" "http://vid.mint.lgbt:3000/feed/channel/UC9pVBqtx2-XrSfKn3BwHrXA" nil nil nil)
     ("Vargskelethor Uncut: Full Joel Streams" "http://vid.mint.lgbt:3000/feed/channel/UCRNCUBq676nUhXyy8AJzD5w" nil nil nil)
     ("Vaush" "http://vid.mint.lgbt:3000/feed/channel/UC1E-JS8L0j1Ei70D9VEFrPQ" nil nil nil)
     ("vicente_795" "http://vid.mint.lgbt:3000/feed/channel/UCz9M_Vlpwy9R8IF6OmXn_Aw" nil nil nil)
     ("videogamedunkey" "http://vid.mint.lgbt:3000/feed/channel/UCsvn_Po0SmunchJYOWpOxMg" nil nil nil)
     ("Vihart" "http://vid.mint.lgbt:3000/feed/channel/UCOGeU-1Fig3rrDjhm9Zs_wg" nil nil nil)
     ("Vinesauce: The Full Sauce" "http://vid.mint.lgbt:3000/feed/channel/UC2_IYqb1Tc_8Azh7rByedPA" nil nil nil)
     ("Vsauce" "http://vid.mint.lgbt:3000/feed/channel/UC6nSFpj9HTCZ5t-N3Rm3-HA" nil nil nil)
     ("Vsauce3" "http://vid.mint.lgbt:3000/feed/channel/UCwmFOfFuvRPI112vR5DNnrA" nil nil nil)
     ("Wadsm" "http://vid.mint.lgbt:3000/feed/channel/UC9S06msqIk1TKpHLVnY2w5g" nil nil nil)
     ("Weest" "http://vid.mint.lgbt:3000/feed/channel/UC61qCGl383-RjaQAYWNogzQ" nil nil nil)
     ("Wilbur Music" "http://vid.mint.lgbt:3000/feed/channel/UC7aqMoMSMbmIaccx1eXAxvQ" nil nil nil)
     ("Wilbur Soot" "http://vid.mint.lgbt:3000/feed/channel/UC1n_PfsVqxllCcnMPlxBIjw" nil nil nil)
     ("Wolfgang's Channel" "http://vid.mint.lgbt:3000/feed/channel/UCsnGwSIHyoYN0kiINAGUKxg" nil nil nil)
     ("Xidnaf" "http://vid.mint.lgbt:3000/feed/channel/UCByBOwwOU5tKddYpsrHiUUw" nil nil nil)
     ("Xidnaf's Secret Channel" "http://vid.mint.lgbt:3000/feed/channel/UCh7Fh7cDnaMXALyileCNgOg" nil nil nil)
     ("YourMovieSucksDOTorg" "http://vid.mint.lgbt:3000/feed/channel/UCSc16oMxxlcJSb9SXkjwMjA" nil nil nil)
     ("슈얀(Shuyan)" "http://vid.mint.lgbt:3000/feed/channel/UCKadAkqLKGQjt__XXL6RR0g" nil nil nil)))
 '(objed-cursor-color "#ff5555")
 '(package-selected-packages
   '(web-beautify shell-pop markdown-preview-mode markdown-mode lolcat flycheck-status-emoji qml-mode neotree highlight-indent-guides highlight-parentheses vterm zone-rainbow omnibox omnisharp auto-complete))
 '(pdf-view-midnight-colors (cons "#f8f8f2" "#1E2029"))
 '(rustic-ansi-faces
   ["#1E2029" "#ff5555" "#50fa7b" "#f1fa8c" "#61bfff" "#ff79c6" "#8be9fd" "#f8f8f2"])
 '(vc-annotate-background "#1E2029")
 '(vc-annotate-color-map
   (list
    (cons 20 "#50fa7b")
    (cons 40 "#85fa80")
    (cons 60 "#bbf986")
    (cons 80 "#f1fa8c")
    (cons 100 "#f5e381")
    (cons 120 "#face76")
    (cons 140 "#ffb86c")
    (cons 160 "#ffa38a")
    (cons 180 "#ff8ea8")
    (cons 200 "#ff79c6")
    (cons 220 "#ff6da0")
    (cons 240 "#ff617a")
    (cons 260 "#ff5555")
    (cons 280 "#d45558")
    (cons 300 "#aa565a")
    (cons 320 "#80565d")
    (cons 340 "#6272a4")
    (cons 360 "#6272a4")))
 '(vc-annotate-very-old-color nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
